# update_fastlane
default_platform(:ios)

platform :ios do

  lane :build do |options|
    identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    run_number = options[:run_number]
    skip_archive = options[:skip_archive]

    match_type = 'adhoc'
    export_method = 'ad-hoc'
    scheme = 'BoostlingoQuickstart'

    #remove archives
    sh(command: "rm -vfr ~/Library/Developer/Xcode/Archives/*")
    
    #remove provisioning profiles to eliminate any conflicts
    sh(command: "rm -vfr ~/Library/MobileDevice/Provisioning\ Profiles/*")

    clear_derived_data

    increment_build_number(
      build_number: run_number.to_s
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      targets: [scheme],
      code_sign_identity: "Apple Distribution",
      bundle_identifier: identifier,
      build_configurations: ["Release"]
    )

    match(
      type: match_type, 
      readonly: is_ci,
      app_identifier: identifier
    )

    evn_variable_name = 'sigh_' + identifier + '_' + match_type + '_profile-path'
    profile_path = ENV[evn_variable_name]

    update_project_provisioning(
      profile: profile_path, 
      build_configuration: "Release"
    )

    cocoapods(
      clean_install: false,
      use_bundle_exec: false
    )

    gym(
      scheme: scheme,
      configuration: "Release",
      clean: true,
      include_bitcode: false,
      output_name: "lspoutbound.ipa",
      export_method: export_method
    )

  end
end
