name: Build and distribute AppCenter

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
        - uses: actions/checkout@v3
        with:
          lfs: true

        - uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

        - name: Install bundler and dependencies
        run: bundle install
        
        - name: Build Boostlingo iOS app
        run: bundle exec fastlane build slack_url:'${{secrets.SLACK_URL}}' run_number:'${{ github.run_number }}' skip_archive:false datadog_api_key:'${{ secrets.DATADOG_API_KEY }}'
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: '${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
